# Q6

## Import Libraries

In [91]:
import os
import numpy as np

## Load Data

In [98]:
data = None
with open('Data' + os.sep + 'hw1q6_data.csv') as fp:
    data = [x.strip().split(',') for x in fp.readlines()]
    
headers = data[0]
class_field = len(headers)-1
data = [[int(x[i]) if i==class_field else float(x[i]) for i in range(len(x))] for x in data[1:]]
data = np.asarray(data)

print('Attributes - ')
print(', '.join(headers))
print()
print('Shape of loaded dataset - ')
print(data.shape)
#     csv_reader = csv.reader(csv_file, delimiter=',')
#     line_count = 0
#     for row in csv_reader:
#         if line_count == 0:
#             print(f'Column names are {", ".join(row)}')
#             line_count += 1
#         else:
#             print(f'\t{row[0]},{row[1]},{row[2]},{row[3]},{row[4]},{row[5]},{row[6]}')
#             line_count += 1
#     print(f'Processed {line_count} lines.')

Attributes - 
Glucose, BloodPressure, SkinThickness, BMI, DiabetesPedigreeFunction, Age, Class

Shape of loaded dataset - 
(768, 7)


In [99]:
data

array([[148.   ,  72.   ,  35.   , ...,   0.627,  50.   ,   1.   ],
       [ 85.   ,  66.   ,  29.   , ...,   0.351,  31.   ,   0.   ],
       [183.   ,  64.   ,   0.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [121.   ,  72.   ,  23.   , ...,   0.245,  30.   ,   0.   ],
       [126.   ,  60.   ,   0.   , ...,   0.349,  47.   ,   1.   ],
       [ 93.   ,  70.   ,  31.   , ...,   0.315,  23.   ,   0.   ]])

## Helper Functions

In [100]:
def countPatients(data):
    diabetic = 0
    nondiabetic = 0
    
    # np.bincount(data[:,6])
    for i in data[:,6]:
        if i == 1:
            diabetic += 1
        else:
            nondiabetic += 1
    
    return (diabetic, nondiabetic)

## (A) Number of diabetic and nondiabetic patients

In [101]:
diabetic, nondiabetic = countPatients(data)
print(f'Number of diabetic patients in the dataset: {diabetic}')
print(f'Number of nondiabetic patients in the dataset: {nondiabetic}')

Number of diabetic patients in the dataset: 268
Number of nondiabetic patients in the dataset: 500


## (B) Missing rate for each feature

In [114]:
def countMissingValue(data):
    missing_values = 0
    for i in data:
        if i == 0:
            missing_values += 1
    return missing_values/len(data) * 100
    
print('Missing Rates:')
for i in range(len(headers)-1):
    percent = countMissingValue(data[:,i])
    print(f'{headers[i]} : {percent} ')

Missing Rates:
Glucose : 0.6510416666666667 
BloodPressure : 4.557291666666666 
SkinThickness : 29.557291666666668 
BMI : 1.4322916666666665 
DiabetesPedigreeFunction : 0.0 
Age : 0.0 


## Removing missing data, rows of patient

In [115]:
missing_data = (data == 0).sum(1)
#remaining_data = data[missing_data == 0, :]
print(type(data))
remaining_data = data[(data[:,0:5]!=0).all(1)]
remaining_data

<class 'numpy.ndarray'>


array([[148.   ,  72.   ,  35.   , ...,   0.627,  50.   ,   1.   ],
       [ 85.   ,  66.   ,  29.   , ...,   0.351,  31.   ,   0.   ],
       [ 89.   ,  66.   ,  23.   , ...,   0.167,  21.   ,   0.   ],
       ...,
       [122.   ,  70.   ,  27.   , ...,   0.34 ,  27.   ,   0.   ],
       [121.   ,  72.   ,  23.   , ...,   0.245,  30.   ,   0.   ],
       [ 93.   ,  70.   ,  31.   , ...,   0.315,  23.   ,   0.   ]])

In [116]:
print('After removing missing data, missing Rates:')
for i in range(len(headers)-1):
    percent = countMissingValue(remaining_data[:,i])
    print(f'{headers[i]} : {percent} ')

Missing Rates:
Glucose : 0.0 
BloodPressure : 0.0 
SkinThickness : 0.0 
BMI : 0.0 
DiabetesPedigreeFunction : 0.0 
Age : 0.0 


## (D) Number of diabetic and nondiabetic patients in remaining data

In [120]:
diabetic, nondiabetic = countPatients(remaining_data)
print(f'Number of diabetic patients in the dataset: {diabetic}')
print(f'Number of nondiabetic patients in the dataset: {nondiabetic}')

Number of diabetic patients in the dataset: 177
Number of nondiabetic patients in the dataset: 355


In [126]:
print('After removing missing data, Statistics:')
for i in range(len(headers)-1):
    mean = np.average(remaining_data[:,i])
    median = np.median(remaining_data[:,i])
    std_deviation = np.std(remaining_data[:,i])
    data_range = np.ptp(remaining_data[:,i])
    percentile_25 = np.percentile(remaining_data[:,i],25)
    percentile_50 = np.percentile(remaining_data[:,i],50)
    percentile_75 = np.percentile(remaining_data[:,i],75)
    print(f'\n{headers[i]} :-> Mean: {mean}, \n\t Median: {median}, \n\t Standard Deviation: {std_deviation}, \n\t Range: {data_range}, '
          f'\n\t 25th percentile: {percentile_25}, \n\t 50th percentile: {percentile_50}, \n\t 75th percentile: {percentile_75}  ')

After removing missing data, Statistics:

Glucose :-> Mean: 121.03007518796993, 
	 Median: 115.0, 
	 Standard Deviation: 30.970077688382087, 
	 Range: 143.0, 
	 25th percentile: 98.75, 
	 50th percentile: 115.0, 
	 75th percentile: 141.25  

BloodPressure :-> Mean: 71.50563909774436, 
	 Median: 72.0, 
	 Standard Deviation: 12.298678262218631, 
	 Range: 86.0, 
	 25th percentile: 64.0, 
	 50th percentile: 72.0, 
	 75th percentile: 80.0  

SkinThickness :-> Mean: 29.18233082706767, 
	 Median: 29.0, 
	 Standard Deviation: 10.51398226832601, 
	 Range: 92.0, 
	 25th percentile: 22.0, 
	 50th percentile: 29.0, 
	 75th percentile: 36.0  

BMI :-> Mean: 32.89022556390977, 
	 Median: 32.8, 
	 Standard Deviation: 6.874638633419096, 
	 Range: 48.89999999999999, 
	 25th percentile: 27.874999999999996, 
	 50th percentile: 32.8, 
	 75th percentile: 36.9  

DiabetesPedigreeFunction :-> Mean: 0.5029661654135338, 
	 Median: 0.416, 
	 Standard Deviation: 0.34422227745866446, 
	 Range: 2.335, 
	 25th perc

In [127]:
#Histogram for Blood Pressure
np.histogram(remaining_data[:,1])

(array([  3,   2,   9,  57, 114, 152, 119,  60,   8,   8]),
 array([ 24. ,  32.6,  41.2,  49.8,  58.4,  67. ,  75.6,  84.2,  92.8,
        101.4, 110. ]))

In [ ]:
#Histogram for 
np.histogram(remaining_data[:,])